image: clever/drone-go:1.6
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  catapult:
    url: $$catapult_url
    application: "mongo-to-s3"
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/mongo-to-s3
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
services:
  - clever/mongo:3.0
script:
  - sudo apt-get update
  - make all
