[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/pathio"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/optimus.v3"
  version = "3.7.0"

[[constraint]]
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/Clever/configure"
  version = "1.0.0"
